### ISSUE TITLE
Duplicate EDMX Items in Solution Explorer

### ISSUE THREAD

**Issue by jtrout** [CZEMacLeod/C3D.MSBuild.Tools.EF6.GenerateViews#2]
Thank you so much for providing this. Not only does it help with not needing the Power Tools anymore, but it also means I don't have to worry about remembering to generate mapping views. Can't tell you how many times I spaced that step and broke the build...

Anyway, now that I have the two entries in my csproj file (EntityView and EntityDeploy), the edmx is duplicated in the Solution Explorer. Am I doing something wrong, is there a way around that, or is that just a side effect we'll have to live with?

    <EntityDeploy Include="iMISEntities.edmx">
      <Generator>EntityModelCodeGenerator</Generator>
      <LastGenOutput>iMISEntities.Designer.cs</LastGenOutput>
    </EntityDeploy>
    <EntityView Include="iMISEntities.edmx">
      <Generator>
      </Generator>
      <CustomToolNamespace>Model</CustomToolNamespace>
    </EntityView>

![image](https://user-images.githubusercontent.com/3289491/152844511-9698e909-3f52-43e5-a5a8-fad4d5b82664.png)

Thanks again!

~Justin

**Comment by CZEMacLeod** [comment]
@jtrout I'm glad you are getting some use out of this tool.
In your case, you are declaring the file `iMISEntities.edmx` twice in your project, with different build actions and metadata. In one case you have the `EntityDeploy` which shows the nested `iMISEntities.Designer.cs` and links the `EntityModelCodeGenerator` generator, in the other it is `EntityView` which is picked up by the nuget package during build and has the `CustomToolNamespace` used to link up the views with the model file.
This allows you to interact with the properties of each declaration in the project file and won't cause any issues as they refer to the same file.
If you are unhappy with this, you could potentially hide the `EntityView` entry by adding
```xml
		<Visible>false</Visible>
```
to the metadata.
```xml
<EntityDeploy Include="iMISEntities.edmx">
  <Generator>EntityModelCodeGenerator</Generator>
  <LastGenOutput>iMISEntities.Designer.cs</LastGenOutput>
</EntityDeploy>
<EntityView Include="iMISEntities.edmx">
  <Generator />
  <Visible>false</Visible>
  <CustomToolNamespace>Model</CustomToolNamespace>
</EntityView>
```

Although then you might forget if you move or edit something or want to change the namespace etc.

You might describe it as a side-effect, but it is really just correct operation, in that the file is doing double duty.
As this isn't actually a problem, I will close the issue here, but if you have any other thoughts feel free to add them.

**Comment by jtrout** [comment]
Perfect, that makes a lot of sense - thanks so much!
