### ISSUE TITLE
Is there a way to use the generated views in a super class of the Context?

### ISSUE THREAD

**Issue by andrewrimmer** [CZEMacLeod/C3D.MSBuild.Tools.EF6.GenerateViews#4]
We have a DB first context like AcmeContext : DbContext, which is automatically created. We then have a superclass of this with our customisations SuperAcmeContext : AcmeContext. However, the superclass cannot access the generated views because they are sealed.

I think if the views were not sealed OR the DbMappingViewCacheTypeAttribute allowed for a parameterised type then it would work. For example [assembly: DbMappingViewCacheTypeAttribute(SuperAcmeContext,...)

Any ideas if there is a workaround?

**Comment by CZEMacLeod** [comment]
@andrewrimmer Interesting issue.

`DbMappingViewCacheTypeAttribute` is part of EF, rather than part of this solution, but also there are some other issues around this, I think.

Unless your `SuperAcmeContext` had no other views applicable, then the hashvalue of that context wouldn't match, and thus the ViewCache class, sealed or not, wouldn't apply.

Also, the code that maps an entity set to the view, probably wouldn't have the same `extentName` (`EntitySetBase.EntityContainer.Name`), so the lookup for GetView wouldn't return the view for the extent.

If the above 2 statements aren't true - that is to say the viewcache actually _could_ be applied to the super context, then simply copying the generated assembly line should work.
You can find the generated class in obj/{Configuration}/{Framework}/EntityViews/{ContextName}.Views.cs
In the sample, you could copy 

```c#
[assembly: DbMappingViewCacheTypeAttribute(
    typeof(NETFrameworkConsoleApp.Models.SchoolContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsaab09e5eb90351ea824967d0dbafd1ab1e408f8dabd87afd5f62c4ce1ef9def7))]
```
out of the generated file and into your `SuperSchoolContext`
```c#
[assembly: DbMappingViewCacheTypeAttribute(
    typeof(NETFrameworkConsoleApp.Models.SuperSchoolContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsaab09e5eb90351ea824967d0dbafd1ab1e408f8dabd87afd5f62c4ce1ef9def7))]
```
The fact that the class is sealed shouldn't make any difference here - you are not altering the class in any way as it is an assembly level attribute.

The only other alternatives I can see, are:

To use a technique like the samples do, to dump the edmx for the super class, and generate the views for that instead.

Or if there is a way to override the way your AcmeContext is 'automatically created'? 
If you could make that class a partial class then you wouldn't need your super class, you could move all your `SuperAcmeContext` code into a partial class file that wouldn't be overwritten by your generation step, and it would merge on compile.

**Comment by CZEMacLeod** [comment]
@andrewrimmer 
Just did a very quick check and the context name is included in the EntityContainer, the Views include the context name, and the hash is different for a super class with no other code in it, so I don't think there is a way to share the views between them.
I would suggest you go with dumping the super-class's edmx and generate the views for that.
The only other suggestion I have, would be to use the package [`EFInteractiveViews`](https://www.nuget.org/packages/EFInteractiveViews/) which allows you to cache the views to disk after they are first generated at runtime. This means a slow start-up on the first run of a new instance, or after an update (when the hashes won't match), but will be of a similar speed to this method there-after.
Depending on how often you update or spin up new instances of your application, this might work better for you.
There is a mechanism to persist the views to a sqlserver, so you could share them between instances in that case, or you could maybe create a persistance mechanism (it is extensible) to pull from an embedded resource, and copy the latest cache file into your project on update.

**Comment by andrewrimmer** [comment]
@CZEMacLeod thanks so much for taking the time to respond with such thorough comments. They have been very helpful and are much appreciated.

We already have a t4 template to generate our DbContext (as it is DB first), so I have refactored this to generate the DbContext as we want it which means we no longer need the super class. This all works great.

I put the ms build task into our solution which all worked fine, until it got to our release pipeline which uses "dotnet publish" for a couple of our apps which is a mix of .net core 3.1 and .net framework 4.7 and it didn't like it. I haven't had time to look into this yet, so for the time being I have created a console app which uses your library to generate the mapping views at design time. This seems  like a reasonable workaround, although does rely on developers remembering to regenerate the mapping views when they make a schema change.

**Comment by CZEMacLeod** [comment]
@andrewrimmer Glad you got a solution.
If you find an issue specifically with this package on netcore/dotnet cli, please feel free to open a new issue.
I did a quick check of the sample applications (both the net5 and net48 ones) using dotnet publish and it seems to work fine.
I will admit I haven't checked a net core 3.1 or a net47 project specifically, but have no reason to suspect it wouldn't work as the dotnet command line version of MSBuild should just use the netstandard 2.1 version of the files. Maybe you need to check which SDKs you have installed for the build process?
